image: golang:1.12

stages:
  - test
  - build

before_script:
  - go mod vendor

lint:
  stage: test
  script:
    - make test-dep
    - make lint

test:
  stage: test
  script:
    - make test-dep
    - make test

build darwin-amd64:
  stage: build
  variables:
    GOOS: darwin
    GOARCH: amd64
  script:
    - go build -o cosmic-cli-$GOOS-$GOARCH github.com/shoekstra/cosmic-cli/cmd/cosmic-cli
  artifacts:
    paths:
    - cosmic-cli-*

build linux-amd64:
  stage: build
  variables:
    GOOS: linux
    GOARCH: amd64
  script:
    - go build -o cosmic-cli-$GOOS-$GOARCH github.com/shoekstra/cosmic-cli/cmd/cosmic-cli
  artifacts:
    paths:
    - cosmic-cli-*

build windows-amd64:
  stage: build
  variables:
    GOOS: windows
    GOARCH: amd64
  script:
    - go build -o cosmic-cli-$GOOS-$GOARCH.exe github.com/shoekstra/cosmic-cli/cmd/cosmic-cli
  artifacts:
    paths:
    - cosmic-cli-*
